export const ON_CARDFRAME_ADD = 'ON_CARDFRAME_ADD';
export const ON_CARDFRAME_REMOVE = 'ON_CARDFRAME_REMOVE';
export const EYE_MODE_CHANGE = 'EYE_MODE_CHANGE';

//主题模块
export const THEMES_CHANGE = 'THEMES_CHANGE';
export const THEMES_TOP_CHANGE = 'THEMES_TOP_CHANGE';


